language: r
r:
 - 3.2
 - devel
cache: packages
warnings_are_errors: true
r_check_args: --as-cran

git:
  depth: 5

r_binary_packages:
 - testthat
  
r_packages:
 - covr
 - devtools
 - knitr
 - rmarkdown
 - roxygen2
   
before_script:
 - R -e "devtools::document()"
  
after_success:
  - Rscript -e "covr::codecov()"
  