language: r
r:
 - 3.2
 - devel
cache: packages
warnings_are_errors: true
r_check_args: --as-cran
sudo: required # Required to use binary packages, which are faster than source installs

git:
  depth: 1
  
r_packages:
 - devtools # Binaries require R 3.4

r_binary_packages:
 - covr
 - knitr
 - rmarkdown
 - roxygen2
 - testthat
   
before_script:
 - R -e "devtools::document()"
 - chmod +x ./_build.sh
 - chmod +x ./_deploy.sh

script:
  - travis_wait 43 ./_build.sh
  - ./_deploy.sh

after_success:
  - Rscript -e "covr::codecov()"
  