language: r
os: linux
dist: xenial
cache: packages
warnings_are_errors: true
r_check_args: --as-cran # --no-manual # Workaround error compiling PDF manual
jobs:
  include:
    - r: 3.2.0 # vdiffr requires 3.4: these tests should fail gracefully.
    - r: 3.4.0 # vdiffr requires 3.4.
    - r: release
      before_install:
        - sudo apt-get -y install libharfbuzz-dev libfribidi-dev
      r_packages: 
        - freetypeharfbuzz
        - pkgdown
      #r_binary_packages:
      # - covr
      # - devtools
      # - knitr
      # - rmarkdown
      # - roxygen2
      # - testthat
      deploy:
        provider: script
        script: Rscript -e 'pkgdown::deploy_site_github()'
        cleanup: false
        skip_cleanup: true
        local_dir: "docs"
        keep-history: true
        on: 
          branch: master
    - r: devel
      r_packages:
         - covr
      after_success:
        - Rscript -e "covr::codecov()"
    - os: osx
      r: release
      before_install:
      - sudo tlmgr install doi titling hyperref
  allow_failures:
   - r: devel # Changes to plot cropping: once on release, run manage_cases()..

git:
  depth: 1

r_packages:
  - devtools

before_script:
  - R -e "devtools::document()"

notifications:
  email:
    on_success: change
    on_failure: change
