language: r
r:
 - 3.2
 - devel
cache: packages
warnings_are_errors: true
r_check_args: --as-cran
env:
 - _R_CHECK_FORCE_SUGGESTS_=false

git:
  depth: 5

r_binary_packages:
 - testthat
  
r_packages:
 - covr
 - devtools
 - knitr
 - rmarkdown
 - roxygen2
   
install:
 - R -e "install.packages('devtools')"
 - R -e "install.packages('knitr')"
 - R -e "install.packages('rmarkdown')"
 - R -e "install.packages('roxygen2')"
 - R -e "install.packages('testthat')"
 - R -e "devtools::document()"
  
after_success:
  - Rscript -e "install.packages('covr'); covr::codecov()"
  